### ISSUE TITLE
1.21 Support?

### ISSUE THREAD

**Issue by Atten007** [OfficialDonut/VisualBukkit#115]
Hello,

I‘m using Visual Bukkit to develop some Plugins for my Minecraft Server. On the 13th June (last week thursday), Minecraft Version 1.21 was released. Because this Version is currently not supported by Visual Bukkit, I wanted to ask you, whether you could add support for this version or not. If yes, it would be really nice!

Greetings,
Atten007 😊

**Comment by OfficialDonut** [comment]
https://github.com/OfficialDonut/VisualBukkit/releases/tag/6.1.0
