### ISSUE TITLE
Request multilingual support

### ISSUE THREAD

**Issue by coremodmc** [OfficialDonut/VisualBukkit#14]
Request to add multi-language API, allowing users to translate VisualBukkit’s display language language into the desired language

**Comment by amyipdev** [comment]
This would be a great thing to have.

**Comment by AstroOrbis** [comment]
I'll help add French support!

**Comment by OfficialDonut** [comment]
Added language support in 3.0.0

**Comment by yebanme** [comment]
How to add the language you need in the program?

**Comment by shmezi** [comment]
https://discord.com/channels/683782858321559582/699651191776215140/830884495817048074
