### ISSUE TITLE
Gamerule Changing and Game Rule Reading

### ISSUE THREAD

**Issue by Gryzle** [OfficialDonut/VisualBukkit#16]
As of now (at least I think) there's no way to change game rules without using a custom block or to read the value of a game rule. This would be useful because game rules can be saved to variables, changed, then later be reverted to their original state.

Edit, I'm not sure how to do flairs.

**Comment by AstroOrbis** [comment]
Maybe just put them all to true and then you know what it is

**Comment by AstroOrbis** [comment]
idk

**Comment by OfficialDonut** [comment]
Added in 2.3.0
