### ISSUE TITLE
GNU General Public License v3.0 Violation

### ISSUE THREAD

**Issue by Gryzle** [OfficialDonut/VisualBukkit#18]
Hi, I've found that your program, Visual Bukkit (specifically version release 2.3.1) violates the terms on conditions stated in the GNU GPL v3.0 license attached to Visual Spigot, which can be found here:

https://github.com/Gryzle/VisualSpigot/blob/main/LICENSE

Visual Bukkit v2.3.1 **violates** the following segments of the GNU GPL v3.0 License:

> You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty, and give all
recipients a copy of this License along with the Program.

> a) The work must carry prominent notices stating that you modified
    it, and giving a relevant date.

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

> If the work has interactive user interfaces, each must display
    Appropriate Legal Notices;

> If the place to
    copy the object code is a network server, the Corresponding Source
    may be on a different server (operated by you or a third party)
    that supports equivalent copying facilities, provided you maintain
    clear directions next to the object code saying where to find the
    Corresponding Source.  Regardless of what server hosts the
    Corresponding Source, you remain obligated to ensure that it is
    available for as long as needed to satisfy these requirements.

> Prohibiting misrepresentation of the origin of that material, or
    requiring that modified versions of such material be marked in
    reasonable ways as different from the original version; or

> Requiring indemnification of licensors and authors of that
    material by anyone who conveys the material (or modified versions of
    it) with contractual assumptions of liability to the recipient, for
    any liability that these contractual assumptions directly impose on
    those licensors and authors.

These conditions must be met before Visual Bukkit 2.3.1 can be distributed, and by having it released without **any** of these conditions being met, you are breaking copyright law.

Thank you for understanding,
Gryzle

**Comment by OfficialDonut** [comment]
This claim is false.
