### ISSUE TITLE
Add windows x86 support in releases pls!

### ISSUE THREAD

**Issue by XIAYM-gh** [OfficialDonut/VisualBukkit#19]
My computer is using Windows 10 x86, and I can't run exe file in releases,
so, please support windows x86 (or upload the jar file.)

**Comment by AstroOrbis** [comment]
I understand the issue but who tf uses 32bit/x86

**Comment by PixelCrafterOS** [comment]
Nobody uses 32 bit. If you're using a 32 bit computer, how can you possibly have enough power to run minecraft, let alone a server?

**Comment by AstroOrbis** [comment]
32bit is an architecture, not an actual measure of computing power :p

**Comment by XIAYM-gh** [comment]
Yes, and I can run Minecraft 1.16.5 smoothly with Optifine, sure, I can run Minecraft server.

**Comment by AstroOrbis** [comment]
Just out of curiosity, what are your PC specs?

**Comment by XIAYM-gh** [comment]
Hummm, sorry, I don't know what mean does the word "specs" is.Does it means "laptop or desktop PC"?

**Comment by AstroOrbis** [comment]
Like what hardware do you use. If you have a Battlestation/desktop PC, then you would list parts, if you have a Laptop PC / Mac you would say which one you have... sry im used to PC lingo lmao

**Comment by XIAYM-gh** [comment]
oh, I'm using HP laptop, but it's outdated.
It's HP laptop EliteBook 8530p. :P

**Comment by 1689295608** [comment]
looks good

**Comment by AstroOrbis** [comment]
nice... MacBook Pro 2019 256gig Touch Bar 8G of ram and waaaaaaay too many things installed 😛

**Comment by XIAYM-gh** [comment]
Haha!
