### ISSUE TITLE
I'm Having Config Troubles.

### ISSUE THREAD

**Issue by BUNNshmit** [OfficialDonut/VisualBukkit#20]
Hello I've been using this program and I just need assistance setting up config files. just in general. I think I just need reassurance that the config tutorial on the Wiki will come out soon. Thx

**Comment by wendellmeset** [comment]
open resource files by clicking resource files in bottom right, create a new text file and name it config.yml, and add whatever you want to it, then do the rest in the code blocks @BUNNshmit

**Comment by BUNNshmit** [comment]
That's very helpful but could you add a bit more information about navigating the config and formatting. Thanks.

**Comment by wendellmeset** [comment]
@BUNNshmit Sorry for being in active, do you have a discord, If you do, please tell me it, and ill send you friend request (My name on discord is Sherlock Holmes) Then i can screen share what to do in more detail!!

**Comment by fineiwill** [comment]
I can use something like that also... (discord is @SammyYT)

> @BUNNshmit Sorry for being in active, do you have a discord, If you do, please tell me it, and ill send you friend request (My name on discord is Sherlock Holmes) Then i can screen share what to do in more detail!!

**Comment by OfficialDonut** [comment]
Added config wiki page: https://github.com/OfficialDonut/VisualBukkit/wiki/Configs
