### ISSUE TITLE
where are any extensions 

### ISSUE THREAD

**Issue by StarTrix28** [OfficialDonut/VisualBukkit#23]
I would like to download some extensions because as far as I know, add more options

**Comment by StarTrix28** [comment]
why

**Comment by StarTrix28** [comment]
I am so stupid so can someone tell me why OfficialDonut Closed my post

**Comment by StarTrix28** [comment]
sorry for my bad english

**Comment by shmezi** [comment]
As you said, you are stupid and don't realize to ask in the support discord, this is for reporting bugs, and such.
Join the discord and people will be able to help you.
https://discord.gg/aFhGtkEc65
