### ISSUE TITLE
Variable New ItemStack cant get the item in players hand

### ISSUE THREAD

**Issue by Tofaa2** [OfficialDonut/VisualBukkit#24]
in java when making lore account to an item you would

`ItemStack is = player.getItemInHand();
ItemMeta im = is.getItemMeta(); 
ArrayList<String> lore = new ArrayList<String>(); 
lore.add("added lore"); 
im.setLore(lore); 
is.setItemMeta(im);`

This isnt something u can do in visual bukkit 

![Screenshot_1](https://user-images.githubusercontent.com/82680183/115119661-95bf2e80-9fba-11eb-85f9-3c01f9cc78dd.png)

**Comment by OfficialDonut** [comment]
[HumanEntity#getItemInHand](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/HumanEntity.html#getItemInHand()) is a deprecated method which is why it's not in Visual Bukkit. The proper way to get the item in the player's main hand is `[PlayerInventory] Get Item In Main Hand` + `[HumanEntity] Get Inventory`.

**Comment by Tofaa2** [comment]
S

> [HumanEntity#getItemInHand](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/HumanEntity.html#getItemInHand()) is a deprecated method which is why it's not in Visual Bukkit. The proper way to get the item in the player's main hand is `[PlayerInventory] Get Item In Main Hand` + `[HumanEntity] Get Inventory`.

So theoretically these 2 seperate blocks should: get the lore, and add to lore ( i know u dont really need the first one im just questioning
![Screenshot_2](https://user-images.githubusercontent.com/82680183/115121436-d4a5b200-9fc3-11eb-8b3d-784f9ca20660.png)

**Comment by OfficialDonut** [comment]
1. You have blocks that return ItemStacks in the ItemMeta fields
2. You set the lore field to a list containing a list and a string which is not what you want.
```
itemVar = get item in main hand
metaVar = get item meta of item
loreVar = get lore of metaVar
add a string to loreVar
set item meta of itemVar to metaVar
```

**Comment by Tofaa2** [comment]
Welp imma mark the issue as closed cause it clearly isnt a bug but it would be nice if u could ss me what that means cause i cant find them
