### ISSUE TITLE
bedenterevent

### ISSUE THREAD

**Issue by pietromarvelli** [OfficialDonut/VisualBukkit#25]
If u set a message on playerbedenterevent, it sends it everytime you click bed (during day/with mobs nearby too)

maybe player.isSleeping() block would fix it

**Comment by OfficialDonut** [comment]
There is a block to check if a player is sleeping: `[LivingEntity] Is Sleeping`

A better solution for your problem is checking if `[PlayerBedEnterEvent] Get Bed Enter Result` is equal to `[PlayerBedEnterEvent.BedEnterResult] OK`
