### ISSUE TITLE
Config not updating

### ISSUE THREAD

**Issue by DeyanVNikolov** [OfficialDonut/VisualBukkit#26]
When I create a config with a few values, it copies into the plugin folder inside the /plugins folder.
However if I update it at later point, it doesn't update. Also if I update the config, but meanwhile someone edited it to own preferences it is going either to overwrite or not copy at all.

**Comment by ghost** [comment]
Send ss your code

> When I create a config with a few values, it copies into the plugin folder inside the /plugins folder.
> However if I update it at later point, it doesn't update. Also if I update the config, but meanwhile someone edited it to own preferences it is going either to overwrite or not copy at all.

**Comment by OfficialDonut** [comment]
This is the intended behavior.
> [Plugin#saveDefaultConfig](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/plugin/Plugin.html#saveDefaultConfig())
> Saves the raw contents of the default config.yml file to the location retrievable by getConfig().
> **This should fail silently if the config.yml already exists.**
