### ISSUE TITLE
Java 8 requirement

### ISSUE THREAD

**Issue by Paul2708** [OfficialDonut/VisualBukkit#3]
Hey,
I just want to ask why Java 8 is required to run the project.
I tried to run it with Java 8 but as I don't have set my `JAVA_HOME` to it I cannot run it.

**Comment by OfficialDonut** [comment]
Newer Java versions don't have JavaFX included. The next update will have an installer with a bundled JRE.

**Comment by Amejonah1200** [comment]
You can do a fat jar with JavaFX inside.

**Comment by OfficialDonut** [comment]
Shading JavaFX 8 is nontrivial, a bundled JRE is a better solution.
