### ISSUE TITLE
Command Argument block isn't showing up

### ISSUE THREAD

**Issue by GearsEngine** [OfficialDonut/VisualBukkit#33]
So I've been using Visual Bukkit for quite a while now, and it's really good (except for the fact that nothing builds on macOS).
But, I've tried making commands... There's no 'Command Argument' block.
If this helps, I have macOS Big Sur installed.

**Comment by ghost** [comment]
If you're talking about the panel on the left, then this block was never there. The command argument is used in blocks, there is no separate block

**Comment by ghost** [comment]
Like

> if statement
>   Is equal
>     argument->0
>     reload
>   reload plugin config
>   [CommandSender] Send Message
>   CommandSender: Command sender
>   Message: "Reloaded!"

**Comment by ghost** [comment]
![Screenshot](https://user-images.githubusercontent.com/73360620/117202327-5b48f480-adf6-11eb-8ab1-91066e66d15b.png)
example

**Comment by GearsEngine** [comment]
Oh, ok thanks for the help!
