### ISSUE TITLE
Pop Up Windows Opening On Sperate Moniter (MacOS)

### ISSUE THREAD

**Issue by baylorhenshaw** [OfficialDonut/VisualBukkit#4]
### Issue
Some windows like the "successful save" pop up open up on the wrong monitor in full screen. I am on MacOS, so this might not be an issue for others. If I use Visual Bukkit on my second monitor, all popups go on my primary. It tabs out of windows I have open, and it is kind of annoying. This is low priority, but it would be nice if it didn't happen. I also just realized it happens when in fullscreen on the primary monitor. It removes the desktop background.

### Screenshots

<img width="439" alt="Screen Shot 2020-07-24 at 3 22 43 PM" src="https://user-images.githubusercontent.com/64096464/88432294-88756a80-cdc1-11ea-9c25-fee682bbe8f2.png">

<img width="2048" alt="Screen Shot 2020-07-24 at 3 27 00 PM" src="https://user-images.githubusercontent.com/64096464/88432599-1fdabd80-cdc2-11ea-9587-2d99015e009a.png">

**Comment by CryLegende** [comment]
I confirm it's the same on Windows 10

**Comment by amyipdev** [comment]
Can reproduce on Fedora Rawhide. Don't think this really matters though... like sure yeah it would be nice but there are other ways to lock your app to just one display, at least over here on Xorg.
