### ISSUE TITLE
VisualBukkit.exe don´t work.

### ISSUE THREAD

**Issue by mitalnet** [OfficialDonut/VisualBukkit#40]
I can´t open program here is report:
![image](https://user-images.githubusercontent.com/85081216/120120239-457fe280-c19c-11eb-9323-5408ba186b66.png)

**Comment by ghost** [comment]
update extensions

**Comment by mitalnet** [comment]
What extension?

**Comment by ghost** [comment]
all

**Comment by OfficialDonut** [comment]
Fixed in version 4.1.1, the error will be gracefully handled.
