### ISSUE TITLE
after I install vault extension.It look like EventListener : InventoryClickEvent are stop working.

### ISSUE THREAD

**Issue by VocanicZ-h** [OfficialDonut/VisualBukkit#43]
vb version : 4.3.1
I've try disable vault exts and the Event look fine. Doublecheck with re-enable it and Its cause the problem again. It's happend only with vault extension.

**Comment by OfficialDonut** [comment]
Please coherently describe the issue and the precise steps to reproduce it (screenshots may help).

**Comment by VocanicZ-h** [comment]
I've try everything and I think maybe its my false cause by wrong syntax.
InventoryClickEvent will not responce if a place this 'Permission]Player Add' anywhere in the project
![image](https://user-images.githubusercontent.com/71394921/122783223-90909f80-d2db-11eb-93e3-5a01eb82a656.png)

in VaultAPI wiki this block need world, player, and perms
`public boolean playerAdd(String world,
                         org.bukkit.OfflinePlayer player,
                         String permission)`

so i dont know what to use in line 1:
![image](https://user-images.githubusercontent.com/71394921/122784327-933fc480-d2dc-11eb-9394-4d4fc9ea4e53.png)

**Comment by OfficialDonut** [comment]
What do you mean by "InventoryClickEvent will not responce"? Are there errors in console?

**Comment by VocanicZ-h** [comment]
Nothing shown in console I've try to print log info at the first line of code in this Event but it print nothing and no error. without Permission] Player Add block. its print out log info correctly.

**Comment by OfficialDonut** [comment]
Check for an error in console when the server starts. Do you have Vault and a permission plugin on the server?
