### ISSUE TITLE
1.8.8

### ISSUE THREAD

**Issue by LuckyMan612** [OfficialDonut/VisualBukkit#46]
Version 1.8.8?

**Comment by ghost** [comment]
If you want 1.8.8 or 1.12.2 support join the Visual Bukkit Patreon at the $15 level (https://www.patreon.com/VisualBukkit)

**Comment by LuckyMan612** [comment]
> If you want 1.8.8 or 1.12.2 support join the Visual Bukkit Patreon at the $15 level (https://www.patreon.com/VisualBukkit)

really?

**Comment by ghost** [comment]
> > If you want 1.8.8 or 1.12.2 support join the Visual Bukkit Patreon at the $15 level (https://www.patreon.com/VisualBukkit)
> 
> really?

Ya

**Comment by LuckyMan612** [comment]
> > > If you want 1.8.8 or 1.12.2 support join the Visual Bukkit Patreon at the $15 level (https://www.patreon.com/VisualBukkit)
> > 
> > 
> > really?
> 
> Ya

shit

**Comment by ghost** [comment]
Donut made this application for free, donut worked and a lot of time for free for those who do not know java but want to create a plugin, so be so grateful to him, VisualBukkit 1.13+, if you want the version below, support donut. he did his best for you
