### ISSUE TITLE
"Block Selector" button not working on windows

### ISSUE THREAD

**Issue by The-Nyla** [OfficialDonut/VisualBukkit#48]
I am stuck using only the green blocks, the "block selector" button does not register being clicked on at all for some reason

![image](https://user-images.githubusercontent.com/79489385/130697180-6e40adb9-79b9-48af-aa1d-22d5c30b470b.png)

**Comment by ghost** [comment]
the __Block selector__ button does not exist

**Comment by ghost** [comment]
Join do VB support discord, check tutorials . Purple blocks -> green button plus

**Comment by TriBuh** [comment]
Same
