### ISSUE TITLE
1.8.8

### ISSUE THREAD

**Issue by LuckyMan612** [OfficialDonut/VisualBukkit#50]
Welcome!
In general I have a question, how to build minecraft plugins version 1.8.8 in this program? I once opened something similar but they wrote me off that you can on patreon, and now I have a question, is it forever or a month?

**Comment by ghost** [comment]
> Welcome!
> In general I have a question, how to build minecraft plugins version 1.8.8 in this program? I once opened something similar but they wrote me off that you can on patreon, and now I have a question, is it forever or a month?

month

**Comment by OfficialDonut** [comment]
Once you download the 1.8 extension jar from Patreon you will obviously have it forever. If you cancel your Patreon pledge you will not be able to download any new jars posted to Patreon and you will no longer have access to the legacy support channel on Discord.
