### ISSUE TITLE
variable set local var needs object?

### ISSUE THREAD

**Issue by thatrandomperson5** [OfficialDonut/VisualBukkit#52]
what is object

**Comment by ghost** [comment]
You are saving something to a variable, right? Place in an object what you want to store in a variable.

**Comment by ghost** [comment]
Please go to the [visual bukkit discord server](https://discord.gg/b4bM9dSgue) instead of posting all your questions here.

**Comment by thatrandomperson5** [comment]
discord says i have to buy a phone to use it

**Comment by ghost** [comment]
> discord says i have to buy a phone to use it

you need to verify your phone number

**Comment by thatrandomperson5** [comment]
I don’t have a phone number

**Comment by zhenaxel** [comment]
> I don’t have a phone number

Одолжите аккаунт у друга, или сделайте что то другое. Решите эту проблему сами

**Comment by ghost** [comment]
> I don’t have a phone number

Borrow an account from a friend, or do something else. Solve this problem yourself. 🔥
