### ISSUE TITLE
where is get player inventory and set nbt blocks?

### ISSUE THREAD

**Issue by thatrandomperson5** [OfficialDonut/VisualBukkit#53]
do they even exists?

**Comment by ghost** [comment]
> do they even exists?

use the discord server for help. if you cannot verify the phone number, please solve this problem differently, but not by sending questions here. To get a player's inventory use `[InventoryHolder] Get Inventory -> your player`

**Comment by ghost** [comment]
Wdym set nbt blocks?

**Comment by thatrandomperson5** [comment]
Ok discord
