### ISSUE TITLE
Download size is too large and may cause issues

### ISSUE THREAD

**Issue by wellsilver** [OfficialDonut/VisualBukkit#54]
TL;DR if possible make _all_ downloads a ZIP
As the download size is too large (122MB) after a minute or two of downloading (at least for me) it stops downloading, now this issue can easily be rectified by downloading it from tools like Winget, but visual bukkit appeals to people with a little knowledge so they may not know how to do this (and might be too lazy to do it), I'm sure a ZIP could possibly half the download size and fix the issue

**Comment by OfficialDonut** [comment]
Zipping only reduces the size by a few MB.
