### ISSUE TITLE
Please add Android support in a future version

### ISSUE THREAD

**Issue by Atten007** [OfficialDonut/VisualBukkit#59]
Hi folks,

When I played Minecraft on my PaperMC server today, the idea to make a job plug-in named „EmeraldJobs“ came me. I want to make this plug-in with Visual bukkit because I’m not very good at spigot plug-in coding. But in the releases tab at the version 5.2.0, I saw that there isn’t an .apk-file for Visual bukkit and that’s not good for me because I’m playing the Java Edition on an Android device and I would also develop spigot plug-ins there. Android devices can also execute Java code natively. Can you please make an .apk-file asap with Android Studio for this very, very nice application?

Sincerely yours,
Atten007😊

**Comment by wendellmeset** [comment]
I feel like remaking the entire application in Android Studio would be quite the job. Thats why they wouldn't do it. However, you never know.

**Comment by shmezi** [comment]
The reason there isn't an apk version is because A. It really doesn't make much sense to do. B. It would be for like 2 people that would want that...

**Comment by Reaper-1709** [comment]
> The reason there isn't an apk version is because A. It really doesn't make much sense to do. B. It would be for like 2 people that would want that...

We actually need that thing as many times we are either out of our homes or we feel lazy to start pc and start vb and stuffs. We can go ahead with our ideas even when we dont have our pc with us.

Whoever needs this please add reaction below

**Comment by Sal4iDev** [comment]
> > The reason there isn't an apk version is because A. It really doesn't make much sense to do. B. It would be for like 2 people that would want that...
> 
> We actually need that thing as many times we are either out of our homes or we feel lazy to start pc and start vb and stuffs. We can go ahead with our ideas even when we dont have our pc. 

boredom. if you have an idea, just write it down in notepad for example, especially if you really want to do it, then you will not be too lazy to start the computer and vb, so there is absolutely no point in this.

**Comment by Tofaa2** [comment]
> > The reason there isn't an apk version is because A. It really doesn't make much sense to do. B. It would be for like 2 people that would want that...
> 
> We actually need that thing as many times we are either out of our homes or we feel lazy to start pc and start vb and stuffs. We can go ahead with our ideas even when we dont have our pc with us.
> 
> Whoever needs this please add reaction below

I have an idea, remake it yourself. You're using free software and want to make it 2x more costly and complex. Beggars cant be choosers

**Comment by Spodey13** [comment]
You can work on the android on your free time like I can't use my pc because I have exams but I like can on my free time use visual bukkit or Evan if I am on vacation not in my house so can you make an Android version

**Comment by Tofaa2** [comment]
> You can work on the android on your free time like I can't use my pc because I have exams but I like can on my free time use visual bukkit or Evan if I am on vacation not in my house so can you make an Android version

yea, make it

**Comment by Spodey13** [comment]
add cuboid

**Comment by SprainedSpark89** [comment]
try using a mobile launcher and use the mod installer and use the jar after it gets fixed
