### ISSUE TITLE
Comments before Else and else if throw build time errors if debug build mode enabled

### ISSUE THREAD

**Issue by MissPotato** [OfficialDonut/VisualBukkit#63]
Version 5.2.1
https://pastebin.com/FmdcJiv9

Disabling the debug mode allows it to compile fine.  I've already tried deleting and re-downloading the plugin in case I forgot to update it. Moving the comment to inside the block allows it to compile fine.

**Comment by OfficialDonut** [comment]
Send a screenshot of the blocks please.

**Comment by MissPotato** [comment]
It seems to only happen with comments included as well. I had a comment at the very beginning that I didn't notice while testing. Here is the minimum to reproduce. 

https://i.imgur.com/5oYqE5E.png

**Comment by OfficialDonut** [comment]
Fixed in 5.2.2
