### ISSUE TITLE
There is no "string from number"

### ISSUE THREAD

**Issue by thatrandomperson5** [OfficialDonut/VisualBukkit#69]
there is a "number from string" block but not this one
i tried using this java snippet:
```java
Integer.toString(game_players) 
```
but i get thie error:
`game_players cannot be resolved to a variable`

**Comment by thatrandomperson5** [comment]
potential fix, using the string to object block

**Comment by thatrandomperson5** [comment]
does not work, i get error on the server: `[23:40:06] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "vb.$tag.PluginMain.GLOBAL_6cd72ffbe287b697ee74534437bbfa56" is null`

**Comment by Sal4iDev** [comment]
> does not work, i get error on the server: `[23:40:06] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "vb.$tag.PluginMain.GLOBAL_6cd72ffbe287b697ee74534437bbfa56" is null`

it means that the global variable is null

**Comment by thatrandomperson5** [comment]
@Sal4iDev Why would it be null, I set it to 0 earlier in the code.

**Comment by Sal4iDev** [comment]
please goto visual bukkit discord and ask for help. send your code and so on

**Comment by thatrandomperson5** [comment]
I can’t. On other questions I’ve been sent there, but I can’t talk there so why would that help?

**Comment by thatrandomperson5** [comment]
help pls, @Sal4iDev
