### ISSUE TITLE
Where's support for 1.19?

### ISSUE THREAD

**Issue by Atten007** [OfficialDonut/VisualBukkit#70]
Hi folks,

I want to make my own plugins with Visual Bukkit for Minecraft version 1.19. But unfortunately, Visual Bukkit hasn't support for 1.19 yet. 1.19 came out on the 7th June of this year. @OfficialDonut can you pls add 1.19 support to visual bukkit asap?

Sincerely yours,
Atten007

**Comment by OfficialDonut** [comment]
Added in version 5.3.0
