### ISSUE TITLE
Compiling 

### ISSUE THREAD

**Issue by ArastaD0t** [OfficialDonut/VisualBukkit#74]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.geometry.Point2D.distance(double, double)" because "this.dragStartLocation" is null

**Comment by ArastaD0t** [comment]
[Log](https://pastebin.com/pJ8s6Xzq)

**Comment by OfficialDonut** [comment]
Send a screenshot of the plugin enable component.

**Comment by ArastaD0t** [comment]
![image](https://user-images.githubusercontent.com/38872983/179655860-7f086c3e-f1ac-4527-9b5b-ed5a31d32c59.png)

**Comment by ArastaD0t** [comment]
![image](https://user-images.githubusercontent.com/38872983/179655913-6d6f2032-3d32-4023-944e-4f9fd1dd4ee3.png)

**Comment by ArastaD0t** [comment]
Sorry my bad...
