### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by Atten007** [OfficialDonut/VisualBukkit#84]
Hello!

On Wednesday the 7th June, the version 1.20 has been released and Visual Bucket hasn't currently support for this, so I wanted to ask you: Can you please add support for this version? This may be very nice! 👍

**Comment by Atten007** [comment]
Hello @OfficialDonut,

When will you add support for Minecraft 1.20?

**Comment by OfficialDonut** [comment]
https://github.com/OfficialDonut/VisualBukkit/releases/tag/v5.5.0
