### ISSUE TITLE
This isn't an issue, Does it work for v1.5.2

### ISSUE THREAD

**Issue by ghost** [OfficialDonut/VisualBukkit#96]
I have no idea if it is compatible for old versions like 1.5.2

**Comment by Tofaa2** [comment]
![image](https://github.com/OfficialDonut/VisualBukkit/assets/82680183/e7ac7612-19cf-43e6-b385-0ffa1ff65c72)

**Comment by Atten007** [comment]
Sorry, only for 1.15.2 and newer.

**Comment by Sal4iDev** [comment]
> Sorry, only for 1.15.2 and newer.

Vb 1.13+
If you want 1.8.8 or 1.12.2 support join the Visual Bukkit Patreon at the $15 level (<https://www.patreon.com/VisualBukkit>)

**Comment by thrailkillr** [comment]
> I have no idea if it is compatible for old versions like 1.5.2

Eaglercraft 1.5.2 is outdated, I know thats what you're here about, use atleast EaglercraftX 1.8.8 with viaversion to use this.
